In [ ]:
import os
import sys
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
#import os
from tqdm import tqdm
import numpy as np
import altair as alt
from vega_datasets import data
alt.data_transformers.enable('default', max_rows=None)

In [ ]:
df_tmalign = pd.read_csv(os.path.join("..", 
                         "tables", 
                         'TM_Align_Results.csv'), index_col=0)

df_tmalign

In [ ]:
df_tn93 = pd.read_csv(os.path.join("..", 
                      "results", "TN93",
                      'tn93_rem2.dst'))

df_tn93

In [ ]:
df_tmalign["Short_Name of Chain_1:"] = ""
df_tmalign["Short_Name of Chain_2:"] = ""

def parseName(name):
    parsed_name = name
    parsed_name = parsed_name.split("_")
    if "Node" in parsed_name[0]:
        parsed_name = parsed_name[0]
    else:
        parsed_name = "_".join(parsed_name[0:3])
    #end if
    return parsed_name
#end method

for index, row in tqdm(df_tmalign.iterrows()):
    id1 = row["Name of Chain_1:"]
    id2 = row["Name of Chain_2:"]
    
    # Parse names
    id1_parsed = parseName(id1)
    id2_parsed = parseName(id2)
    
    # dfmi.loc[:, ('one', 'second')]
    
    #df_tmalign.loc[:, ("Short_Name of Chain_1:", index)] = id1_parsed
    #df_tmalign.loc[:, ("Short_Name of Chain_2:", index)] = id2_parsed
    
    df_tmalign["Short_Name of Chain_1:"][index] = id1_parsed
    df_tmalign["Short_Name of Chain_2:"][index] = id2_parsed
#end for

In [ ]:
df_tmalign

In [ ]:
df_tmalign["TN93"] = ""

for index, row in tqdm(df_tn93.iterrows()):
    id1_parsed = parseName(row["ID1"])
    id2_parsed = parseName(row["ID2"])
    distance =   row["Distance"]
    
    df = df_tmalign[df_tmalign["Short_Name of Chain_2:"] == id1_parsed]
    df2 = df[df["Short_Name of Chain_1:"] == id2_parsed]
    df_tmalign["TN93"][df2.index] = distance
    
    df = df_tmalign[df_tmalign["Short_Name of Chain_1:"] == id1_parsed]
    df2 = df[df["Short_Name of Chain_2:"] == id2_parsed]
    df_tmalign["TN93"][df2.index] = distance
        
    #break
    #print(df2.index[0])
    #break

In [ ]:
df

In [ ]:
df2

In [ ]:
df_tmalign

In [ ]:
df_tmalign[df_tmalign["TN93"] == ""]

In [ ]:
df_tmalign.to_csv(os.path.join("..", 
                         "tables", 
                         'TM_Align_Results_with_GeneticDistance.csv'))

In [ ]:

source = df_tmalign

rmsd = alt.Chart(source).mark_bar().encode(
    alt.X("RMSD=", bin=alt.Bin(step=0.001), title='RMSD'),
    y='count()',
)

tm = alt.Chart(source).mark_bar().encode(
    alt.X("Normalized_Average_TM_Score", bin=alt.Bin(step=0.001), title='TM-Score (Averaged)'),
    y='count()',
)

source["TN93"] = pd.to_numeric(source["TN93"])

tn93 = alt.Chart(source).mark_bar().encode(
    alt.X("TN93", bin=alt.Bin(step=0.005
                                ), title='TN93 genetic distance'),
    y='count()',
)

rmsd | tm | tn93

In [ ]:
source = df_tmalign

chart = alt.Chart(source).mark_point(size=1).encode(
    x=alt.X('RMSD=', title='RMSD'),
    y=alt.Y('Normalized_Average_TM_Score', title='TM-Score (Averaged)')
)

chart_flip = alt.Chart(source).mark_circle(size=5).encode(
    y=alt.Y('RMSD='),
    x=alt.X('Normalized_Average_TM_Score')
)

chart | chart_flip


chart

In [ ]:
source = df_tmalign

chart = alt.Chart(source).mark_point(size=1).encode(
    x=alt.X('TN93', title='TN93'),
    y=alt.Y('RMSD=', title='RMSD')
)

chart2 = alt.Chart(source).mark_point(size=1).encode(
    x=alt.X('TN93', title='TN93'),
    y=alt.Y('Normalized_Average_TM_Score', title='TM Score (Averaged)')
)

#chart_flip = alt.Chart(source).mark_circle(size=5).encode(
#    y=alt.Y('RMSD='),
#    x=alt.X('Normalized_Average_TM_Score')
#)

#chart | chart_flip


chart | chart2

#c  = alt.HConcat(chart, chart2)
#c = chart | chart2
#c.save('mychart.png', scale_factor=2.0)

In [ ]:
source = df_tmalign

chart = alt.Chart(source).mark_line(size=2).encode(
    x=alt.X('TN93', title='TN93'),
    y=alt.Y('RMSD=', title='RMSD')
)

chart2 = alt.Chart(source).mark_line(size=2).encode(
    x=alt.X('TN93', title='TN93'),
    y=alt.Y('Normalized_Average_TM_Score', title='TM Score (Averaged)')
)

#chart_flip = alt.Chart(source).mark_circle(size=5).encode(
#    y=alt.Y('RMSD='),
#    x=alt.X('Normalized_Average_TM_Score')
#)

#chart | chart_flip


#chart

chart | chart2

# End of file

In [ ]:
# Name of Chain_1:	Name of Chain_2:
 
    
"""
ID1,ID2,Distance
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,NM_022685_2_Rattus_norvegicus_RRAD_and_GEM_like_GTPase_2_Rem2_mRNA_1,0.138878
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,NM_080726_3_Mus_musculus_rad_and_gem_related_GTP_binding_protein_2_Rem2_mRNA_1,0.137229
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,NM_173527_3_Homo_sapiens_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_1,0.0888912
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node104,0.0566037
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node105,0.0597809
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node107,0.06196
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node110,0.0587744
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node111,0.0598314

""" 

#df_tmalign["TN93_GENETIC_DISTANCE"] = ""
results_dict = {}
count = 0
for index, row in tqdm(df_tmalign.iterrows()):
    #print(row["firstname"])
    id1 = row["Name of Chain_1:"]
    id2 = row["Name of Chain_2:"]
    
    #print(id1, id2)
    
    # Parse names
    id1_parsed = parseName(id1)
    id2_parsed = parseName(id2)
    
    #print(id1_parsed, id2_parsed)
    
    #for index2, row2 in df_tn93.iterrows():
    #    if id1_parsed in row2["ID1"] and id2_parsed in row2["ID2"]: # Match
    #        row["TN93_GENETIC_DISTANCE"] = row2["Distance"]
    #    #end if
    ##end inner for
    
    #results_dict.update({id1_parsed: {id2_parsed: {"RMSD=": row["RMSD="],
    #                                               "Normalized_Average_TM_Score": row["Normalized_Average_TM_Score"]}}})

    if id1_parsed in results_dict:
        results_dict[id1_parsed].update({id2_parsed: {"RMSD=": row["RMSD="],
                                                      "Normalized_Average_TM_Score": row["Normalized_Average_TM_Score"]}})
    else:
        results_dict[id1_parsed] = {id2_parsed: {"RMSD=": row["RMSD="],
                                                 "Normalized_Average_TM_Score": row["Normalized_Average_TM_Score"]}}
    #end if
#end outer for

In [ ]:
"""
ID1,ID2,Distance
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,NM_022685_2_Rattus_norvegicus_RRAD_and_GEM_like_GTPase_2_Rem2_mRNA_1,0.138878
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,NM_080726_3_Mus_musculus_rad_and_gem_related_GTP_binding_protein_2_Rem2_mRNA_1,0.137229
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,NM_173527_3_Homo_sapiens_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_1,0.0888912
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node104,0.0566037
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node105,0.0597809
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node107,0.06196
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node110,0.0587744
NM_001192708_1_Bos_taurus_RRAD_and_GEM_like_GTPase_2_REM2_mRNA_2,Node111,0.0598314

""" 

results_dict_tn93 = {}

for index, row in df_tn93.iterrows():
    #if id1_parsed in row2["ID1"] and id2_parsed in row2["ID2"]: # Match
    #    row["TN93_GENETIC_DISTANCE"] = row2["Distance"]
    #end if
    
    id1_parsed = parseName(row["ID1"])
    id2_parsed = parseName(row["ID2"])
    
    print(id1_parsed, id2_parsed)
    if id1_parsed in results_dict_tn93:
        results_dict_tn93[id1_parsed].update({id2_parsed: {"TN93": row["Distance"]}})
    else:
        results_dict_tn93[id1_parsed] = {id2_parsed: {"TN93": row["Distance"]}}
    #end if
    
    #continue
    #if id1_parsed in results_dict.keys():
    #    results_dict[id1_parsed].update({id2_parsed:{"TN93_GENETIC_DISTANCE": row["Distance"]}})
    #else:
    #    results_dict[id2_parsed].update({id1_parsed:{"TN93_GENETIC_DISTANCE": row["Distance"]}})
    #print(results_dict.get(id1_parsed), 0)
    #x = results_dict.get(id1_parsed, 0)
    #y = results_dict.get(id2_parsed, 0)
    
    #if x == 0 and y != 0:
    #    if results_dict.get(id1_parsed, 0) == 0:
    #        results_dict[id2_parsed][id1_parsed].update({"TN93_GENETIC_DISTANCE": row["Distance"]})
    #elif x != 0 and y == 0:
    #    results_dict[id1_parsed][id2_parsed].update({"TN93_GENETIC_DISTANCE": row["Distance"]})
    #else:
    #    print(x, y)
    #end if
        
#end inner for

In [ ]:

# We will add things to the 'results_dict' dictionary
# We need to go two levels down for it

for k in tqdm(results_dict.keys()):
    for k2 in results_dict[k].keys():
        pair = [k, k2]
        
        for k_t in results_dict_tn93.keys():
            for k_t2 in results_dict_tn93.keys():
                pair_t = [k_t, k_t2]
                
                if set(pair) == set(pair_t): # Match
                    #print('match')
                    try:
                        results_dict[k][k2].update({"TN93_GENETIC_DISTANCE": results_dict_tn93[k_t][k_t2]['TN93']})
                    except:
                        results_dict[k][k2].update({"TN93_GENETIC_DISTANCE": results_dict_tn93[k_t2][k_t]['TN93']})
                    #end try
                        
                    if results_dict[k][k2].get("TN93_GENETIC_DISTANCE", np.nan) == np.nan:
                        try:
                            results_dict[k2][k].update({"TN93_GENETIC_DISTANCE": results_dict_tn93[k_t][k_t2]['TN93']})
                        except:
                            results_dict[k2][k].update({"TN93_GENETIC_DISTANCE": results_dict_tn93[k_t2][k_t]['TN93']})
                        #endtry
                    #end if
                #end if
            #end for
        #end for
    #end for
#end for

In [ ]:
#results_dict
## dict to df
## df to csv

formatted_dict = {}
count = 1

for k in results_dict.keys():
    for k2 in results_dict[k].keys():
        temp_dict = {}
        for item in results_dict[k][k2].keys():
            temp_dict.update({item : results_dict[k][k2][item]})
        #end for
        
        formatted_dict[count] = {"ID1": k,
                                 "ID2": k2}
        formatted_dict[count].update(temp_dict)                           
        
        count +=1 
    #end for
    
#end for

In [ ]:
df = pd.DataFrame.from_dict(formatted_dict, orient="index")
df